// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -package=mock_usecase -source=ports.go -destination=../../_mock/usecase/ports_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ajiperdana/parkir-pintar/services/reservation/internal/domain"
	usecase "github.com/ajiperdana/parkir-pintar/services/reservation/internal/usecase"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReservationRepo is a mock of ReservationRepo interface.
type MockReservationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepoMockRecorder
	isgomock struct{}
}

// MockReservationRepoMockRecorder is the mock recorder for MockReservationRepo.
type MockReservationRepoMockRecorder struct {
	mock *MockReservationRepo
}

// NewMockReservationRepo creates a new mock instance.
func NewMockReservationRepo(ctrl *gomock.Controller) *MockReservationRepo {
	mock := &MockReservationRepo{ctrl: ctrl}
	mock.recorder = &MockReservationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepo) EXPECT() *MockReservationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReservationRepo) Create(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReservationRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReservationRepo)(nil).Create), ctx, r)
}

// FindActiveByDriverID mocks base method.
func (m *MockReservationRepo) FindActiveByDriverID(ctx context.Context, driverID string) (*domain.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDriverID", ctx, driverID)
	ret0, _ := ret[0].(*domain.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDriverID indicates an expected call of FindActiveByDriverID.
func (mr *MockReservationRepoMockRecorder) FindActiveByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDriverID", reflect.TypeOf((*MockReservationRepo)(nil).FindActiveByDriverID), ctx, driverID)
}

// FindExpiredConfirmed mocks base method.
func (m *MockReservationRepo) FindExpiredConfirmed(ctx context.Context, now time.Time, limit int) ([]*domain.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiredConfirmed", ctx, now, limit)
	ret0, _ := ret[0].([]*domain.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiredConfirmed indicates an expected call of FindExpiredConfirmed.
func (mr *MockReservationRepoMockRecorder) FindExpiredConfirmed(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiredConfirmed", reflect.TypeOf((*MockReservationRepo)(nil).FindExpiredConfirmed), ctx, now, limit)
}

// GetByID mocks base method.
func (m *MockReservationRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReservationRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReservationRepo)(nil).GetByID), ctx, id)
}

// UpdateState mocks base method.
func (m *MockReservationRepo) UpdateState(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockReservationRepoMockRecorder) UpdateState(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockReservationRepo)(nil).UpdateState), ctx, r)
}

// MockSpotRepo is a mock of SpotRepo interface.
type MockSpotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSpotRepoMockRecorder
	isgomock struct{}
}

// MockSpotRepoMockRecorder is the mock recorder for MockSpotRepo.
type MockSpotRepoMockRecorder struct {
	mock *MockSpotRepo
}

// NewMockSpotRepo creates a new mock instance.
func NewMockSpotRepo(ctrl *gomock.Controller) *MockSpotRepo {
	mock := &MockSpotRepo{ctrl: ctrl}
	mock.recorder = &MockSpotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotRepo) EXPECT() *MockSpotRepoMockRecorder {
	return m.recorder
}

// GetAvailability mocks base method.
func (m *MockSpotRepo) GetAvailability(ctx context.Context) (*usecase.Availability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailability", ctx)
	ret0, _ := ret[0].(*usecase.Availability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailability indicates an expected call of GetAvailability.
func (mr *MockSpotRepoMockRecorder) GetAvailability(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailability", reflect.TypeOf((*MockSpotRepo)(nil).GetAvailability), ctx)
}

// GetByID mocks base method.
func (m *MockSpotRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Spot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Spot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSpotRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSpotRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSpotRepo) List(ctx context.Context, filter usecase.SpotFilter) ([]*domain.Spot, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Spot)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSpotRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSpotRepo)(nil).List), ctx, filter)
}

// MarkAvailable mocks base method.
func (m *MockSpotRepo) MarkAvailable(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAvailable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAvailable indicates an expected call of MarkAvailable.
func (mr *MockSpotRepoMockRecorder) MarkAvailable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAvailable", reflect.TypeOf((*MockSpotRepo)(nil).MarkAvailable), ctx, id)
}

// MarkHeld mocks base method.
func (m *MockSpotRepo) MarkHeld(ctx context.Context, id uuid.UUID, version int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkHeld", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkHeld indicates an expected call of MarkHeld.
func (mr *MockSpotRepoMockRecorder) MarkHeld(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkHeld", reflect.TypeOf((*MockSpotRepo)(nil).MarkHeld), ctx, id, version)
}

// MarkOccupied mocks base method.
func (m *MockSpotRepo) MarkOccupied(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOccupied", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOccupied indicates an expected call of MarkOccupied.
func (mr *MockSpotRepoMockRecorder) MarkOccupied(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOccupied", reflect.TypeOf((*MockSpotRepo)(nil).MarkOccupied), ctx, id)
}

// PickAvailable mocks base method.
func (m *MockSpotRepo) PickAvailable(ctx context.Context, vt domain.VehicleType) (*domain.Spot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickAvailable", ctx, vt)
	ret0, _ := ret[0].(*domain.Spot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickAvailable indicates an expected call of PickAvailable.
func (mr *MockSpotRepoMockRecorder) PickAvailable(ctx, vt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickAvailable", reflect.TypeOf((*MockSpotRepo)(nil).PickAvailable), ctx, vt)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishReservationCancelled mocks base method.
func (m *MockEventPublisher) PublishReservationCancelled(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationCancelled", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationCancelled indicates an expected call of PublishReservationCancelled.
func (mr *MockEventPublisherMockRecorder) PublishReservationCancelled(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationCancelled", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationCancelled), ctx, r)
}

// PublishReservationCheckedIn mocks base method.
func (m *MockEventPublisher) PublishReservationCheckedIn(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationCheckedIn", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationCheckedIn indicates an expected call of PublishReservationCheckedIn.
func (mr *MockEventPublisherMockRecorder) PublishReservationCheckedIn(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationCheckedIn", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationCheckedIn), ctx, r)
}

// PublishReservationCheckedOut mocks base method.
func (m *MockEventPublisher) PublishReservationCheckedOut(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationCheckedOut", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationCheckedOut indicates an expected call of PublishReservationCheckedOut.
func (mr *MockEventPublisherMockRecorder) PublishReservationCheckedOut(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationCheckedOut", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationCheckedOut), ctx, r)
}

// PublishReservationConfirmed mocks base method.
func (m *MockEventPublisher) PublishReservationConfirmed(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationConfirmed", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationConfirmed indicates an expected call of PublishReservationConfirmed.
func (mr *MockEventPublisherMockRecorder) PublishReservationConfirmed(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationConfirmed", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationConfirmed), ctx, r)
}

// PublishReservationExpired mocks base method.
func (m *MockEventPublisher) PublishReservationExpired(ctx context.Context, r *domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationExpired", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationExpired indicates an expected call of PublishReservationExpired.
func (mr *MockEventPublisherMockRecorder) PublishReservationExpired(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationExpired", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationExpired), ctx, r)
}

// MockLocker is a mock of Locker interface.
type MockLocker struct {
	ctrl     *gomock.Controller
	recorder *MockLockerMockRecorder
	isgomock struct{}
}

// MockLockerMockRecorder is the mock recorder for MockLocker.
type MockLockerMockRecorder struct {
	mock *MockLocker
}

// NewMockLocker creates a new mock instance.
func NewMockLocker(ctrl *gomock.Controller) *MockLocker {
	mock := &MockLocker{ctrl: ctrl}
	mock.recorder = &MockLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocker) EXPECT() *MockLockerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLocker) Acquire(ctx context.Context, key string, ttl time.Duration) (func(context.Context) error, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key, ttl)
	ret0, _ := ret[0].(func(context.Context) error)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLockerMockRecorder) Acquire(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLocker)(nil).Acquire), ctx, key, ttl)
}

// MockIdempotencyService is a mock of IdempotencyService interface.
type MockIdempotencyService struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyServiceMockRecorder
	isgomock struct{}
}

// MockIdempotencyServiceMockRecorder is the mock recorder for MockIdempotencyService.
type MockIdempotencyServiceMockRecorder struct {
	mock *MockIdempotencyService
}

// NewMockIdempotencyService creates a new mock instance.
func NewMockIdempotencyService(ctrl *gomock.Controller) *MockIdempotencyService {
	mock := &MockIdempotencyService{ctrl: ctrl}
	mock.recorder = &MockIdempotencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyService) EXPECT() *MockIdempotencyServiceMockRecorder {
	return m.recorder
}

// Wrap mocks base method.
func (m *MockIdempotencyService) Wrap(ctx context.Context, key, requestKey string, payload []byte, fn func(context.Context) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", ctx, key, requestKey, payload, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wrap indicates an expected call of Wrap.
func (mr *MockIdempotencyServiceMockRecorder) Wrap(ctx, key, requestKey, payload, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockIdempotencyService)(nil).Wrap), ctx, key, requestKey, payload, fn)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockOverdueChecker is a mock of OverdueChecker interface.
type MockOverdueChecker struct {
	ctrl     *gomock.Controller
	recorder *MockOverdueCheckerMockRecorder
	isgomock struct{}
}

// MockOverdueCheckerMockRecorder is the mock recorder for MockOverdueChecker.
type MockOverdueCheckerMockRecorder struct {
	mock *MockOverdueChecker
}

// NewMockOverdueChecker creates a new mock instance.
func NewMockOverdueChecker(ctrl *gomock.Controller) *MockOverdueChecker {
	mock := &MockOverdueChecker{ctrl: ctrl}
	mock.recorder = &MockOverdueCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverdueChecker) EXPECT() *MockOverdueCheckerMockRecorder {
	return m.recorder
}

// CountOverdueByDriverID mocks base method.
func (m *MockOverdueChecker) CountOverdueByDriverID(ctx context.Context, driverID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverdueByDriverID", ctx, driverID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverdueByDriverID indicates an expected call of CountOverdueByDriverID.
func (mr *MockOverdueCheckerMockRecorder) CountOverdueByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverdueByDriverID", reflect.TypeOf((*MockOverdueChecker)(nil).CountOverdueByDriverID), ctx, driverID)
}
