// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -package=mock_idempotency -source=store.go -destination=../_mock/idempotency/store_mock.go
//

// Package mock_idempotency is a generated GoMock package.
package mock_idempotency

import (
	context "context"
	reflect "reflect"
	time "time"

	idempotency "github.com/ajiperdana/parkir-pintar/pkg/idempotency"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockStore) Begin(ctx context.Context, key, requestHash string, ttl time.Duration) (*idempotency.Record, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, key, requestHash, ttl)
	ret0, _ := ret[0].(*idempotency.Record)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Begin indicates an expected call of Begin.
func (mr *MockStoreMockRecorder) Begin(ctx, key, requestHash, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockStore)(nil).Begin), ctx, key, requestHash, ttl)
}

// Complete mocks base method.
func (m *MockStore) Complete(ctx context.Context, key string, status int, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, key, status, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockStoreMockRecorder) Complete(ctx, key, status, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockStore)(nil).Complete), ctx, key, status, body)
}

// Fail mocks base method.
func (m *MockStore) Fail(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fail", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fail indicates an expected call of Fail.
func (mr *MockStoreMockRecorder) Fail(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockStore)(nil).Fail), ctx, key)
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, key string) (*idempotency.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*idempotency.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, key)
}
