// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -package=mock_usecase -source=ports.go -destination=../../_mock/usecase/ports_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/ajiperdana/parkir-pintar/services/notification/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockContactRepo is a mock of ContactRepo interface.
type MockContactRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepoMockRecorder
	isgomock struct{}
}

// MockContactRepoMockRecorder is the mock recorder for MockContactRepo.
type MockContactRepoMockRecorder struct {
	mock *MockContactRepo
}

// NewMockContactRepo creates a new mock instance.
func NewMockContactRepo(ctrl *gomock.Controller) *MockContactRepo {
	mock := &MockContactRepo{ctrl: ctrl}
	mock.recorder = &MockContactRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactRepo) EXPECT() *MockContactRepoMockRecorder {
	return m.recorder
}

// GetByDriverID mocks base method.
func (m *MockContactRepo) GetByDriverID(ctx context.Context, driverID string) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDriverID", ctx, driverID)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDriverID indicates an expected call of GetByDriverID.
func (mr *MockContactRepoMockRecorder) GetByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDriverID", reflect.TypeOf((*MockContactRepo)(nil).GetByDriverID), ctx, driverID)
}

// Upsert mocks base method.
func (m *MockContactRepo) Upsert(ctx context.Context, c *domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockContactRepoMockRecorder) Upsert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockContactRepo)(nil).Upsert), ctx, c)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// ExistsForEventID mocks base method.
func (m *MockNotificationRepo) ExistsForEventID(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsForEventID", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsForEventID indicates an expected call of ExistsForEventID.
func (mr *MockNotificationRepoMockRecorder) ExistsForEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsForEventID", reflect.TypeOf((*MockNotificationRepo)(nil).ExistsForEventID), ctx, eventID)
}

// GetByID mocks base method.
func (m *MockNotificationRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationRepo)(nil).GetByID), ctx, id)
}

// SaveNew mocks base method.
func (m *MockNotificationRepo) SaveNew(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNew", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNew indicates an expected call of SaveNew.
func (mr *MockNotificationRepoMockRecorder) SaveNew(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNew", reflect.TypeOf((*MockNotificationRepo)(nil).SaveNew), ctx, n)
}

// UpdateStatus mocks base method.
func (m *MockNotificationRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.Status, sentAt *any, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, sentAt, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationRepoMockRecorder) UpdateStatus(ctx, id, status, sentAt, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateStatus), ctx, id, status, sentAt, lastErr)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEmailSender) Send(ctx context.Context, toEmail, toName, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, toEmail, toName, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailSenderMockRecorder) Send(ctx, toEmail, toName, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailSender)(nil).Send), ctx, toEmail, toName, subject, body)
}

// MockTemplateRenderer is a mock of TemplateRenderer interface.
type MockTemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRendererMockRecorder
	isgomock struct{}
}

// MockTemplateRendererMockRecorder is the mock recorder for MockTemplateRenderer.
type MockTemplateRendererMockRecorder struct {
	mock *MockTemplateRenderer
}

// NewMockTemplateRenderer creates a new mock instance.
func NewMockTemplateRenderer(ctrl *gomock.Controller) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{ctrl: ctrl}
	mock.recorder = &MockTemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRenderer) EXPECT() *MockTemplateRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockTemplateRenderer) Render(kind domain.Kind, vars map[string]any) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", kind, vars)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Render indicates an expected call of Render.
func (mr *MockTemplateRendererMockRecorder) Render(kind, vars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockTemplateRenderer)(nil).Render), kind, vars)
}

// MockDLQPublisher is a mock of DLQPublisher interface.
type MockDLQPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockDLQPublisherMockRecorder
	isgomock struct{}
}

// MockDLQPublisherMockRecorder is the mock recorder for MockDLQPublisher.
type MockDLQPublisherMockRecorder struct {
	mock *MockDLQPublisher
}

// NewMockDLQPublisher creates a new mock instance.
func NewMockDLQPublisher(ctrl *gomock.Controller) *MockDLQPublisher {
	mock := &MockDLQPublisher{ctrl: ctrl}
	mock.recorder = &MockDLQPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLQPublisher) EXPECT() *MockDLQPublisherMockRecorder {
	return m.recorder
}

// PublishDLQ mocks base method.
func (m *MockDLQPublisher) PublishDLQ(ctx context.Context, originalSubject, eventID string, originalPayload []byte, errReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDLQ", ctx, originalSubject, eventID, originalPayload, errReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDLQ indicates an expected call of PublishDLQ.
func (mr *MockDLQPublisherMockRecorder) PublishDLQ(ctx, originalSubject, eventID, originalPayload, errReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDLQ", reflect.TypeOf((*MockDLQPublisher)(nil).PublishDLQ), ctx, originalSubject, eventID, originalPayload, errReason)
}
