// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen -package=mock_usecase -source=handlers.go -destination=../../_mock/usecase/handlers_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	eventbus "github.com/ajiperdana/parkir-pintar/pkg/eventbus"
	domain "github.com/ajiperdana/parkir-pintar/services/billing/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceRepo is a mock of InvoiceRepo interface.
type MockInvoiceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepoMockRecorder
	isgomock struct{}
}

// MockInvoiceRepoMockRecorder is the mock recorder for MockInvoiceRepo.
type MockInvoiceRepoMockRecorder struct {
	mock *MockInvoiceRepo
}

// NewMockInvoiceRepo creates a new mock instance.
func NewMockInvoiceRepo(ctrl *gomock.Controller) *MockInvoiceRepo {
	mock := &MockInvoiceRepo{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepo) EXPECT() *MockInvoiceRepoMockRecorder {
	return m.recorder
}

// CountOverdueByDriver mocks base method.
func (m *MockInvoiceRepo) CountOverdueByDriver(ctx context.Context, driverID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverdueByDriver", ctx, driverID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverdueByDriver indicates an expected call of CountOverdueByDriver.
func (mr *MockInvoiceRepoMockRecorder) CountOverdueByDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverdueByDriver", reflect.TypeOf((*MockInvoiceRepo)(nil).CountOverdueByDriver), ctx, driverID)
}

// FindOverdueCandidates mocks base method.
func (m *MockInvoiceRepo) FindOverdueCandidates(ctx context.Context, issuedBefore time.Time, limit int) ([]*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdueCandidates", ctx, issuedBefore, limit)
	ret0, _ := ret[0].([]*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdueCandidates indicates an expected call of FindOverdueCandidates.
func (mr *MockInvoiceRepoMockRecorder) FindOverdueCandidates(ctx, issuedBefore, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdueCandidates", reflect.TypeOf((*MockInvoiceRepo)(nil).FindOverdueCandidates), ctx, issuedBefore, limit)
}

// GetByID mocks base method.
func (m *MockInvoiceRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvoiceRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetByID), ctx, id)
}

// GetByReservationID mocks base method.
func (m *MockInvoiceRepo) GetByReservationID(ctx context.Context, reservationID uuid.UUID) (*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReservationID", ctx, reservationID)
	ret0, _ := ret[0].(*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReservationID indicates an expected call of GetByReservationID.
func (mr *MockInvoiceRepoMockRecorder) GetByReservationID(ctx, reservationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReservationID", reflect.TypeOf((*MockInvoiceRepo)(nil).GetByReservationID), ctx, reservationID)
}

// Save mocks base method.
func (m *MockInvoiceRepo) Save(ctx context.Context, inv *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInvoiceRepoMockRecorder) Save(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInvoiceRepo)(nil).Save), ctx, inv)
}

// MockEventLog is a mock of EventLog interface.
type MockEventLog struct {
	ctrl     *gomock.Controller
	recorder *MockEventLogMockRecorder
	isgomock struct{}
}

// MockEventLogMockRecorder is the mock recorder for MockEventLog.
type MockEventLogMockRecorder struct {
	mock *MockEventLog
}

// NewMockEventLog creates a new mock instance.
func NewMockEventLog(ctrl *gomock.Controller) *MockEventLog {
	mock := &MockEventLog{ctrl: ctrl}
	mock.recorder = &MockEventLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLog) EXPECT() *MockEventLogMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEventLog) Append(ctx context.Context, env eventbus.Envelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, env)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockEventLogMockRecorder) Append(ctx, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEventLog)(nil).Append), ctx, env)
}

// Seen mocks base method.
func (m *MockEventLog) Seen(ctx context.Context, sourceEventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seen", ctx, sourceEventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seen indicates an expected call of Seen.
func (mr *MockEventLogMockRecorder) Seen(ctx, sourceEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seen", reflect.TypeOf((*MockEventLog)(nil).Seen), ctx, sourceEventID)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishInvoiceIssued mocks base method.
func (m *MockEventPublisher) PublishInvoiceIssued(ctx context.Context, inv *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInvoiceIssued", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInvoiceIssued indicates an expected call of PublishInvoiceIssued.
func (mr *MockEventPublisherMockRecorder) PublishInvoiceIssued(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInvoiceIssued", reflect.TypeOf((*MockEventPublisher)(nil).PublishInvoiceIssued), ctx, inv)
}

// PublishInvoiceOverdue mocks base method.
func (m *MockEventPublisher) PublishInvoiceOverdue(ctx context.Context, inv *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInvoiceOverdue", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInvoiceOverdue indicates an expected call of PublishInvoiceOverdue.
func (mr *MockEventPublisherMockRecorder) PublishInvoiceOverdue(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInvoiceOverdue", reflect.TypeOf((*MockEventPublisher)(nil).PublishInvoiceOverdue), ctx, inv)
}

// PublishInvoicePaid mocks base method.
func (m *MockEventPublisher) PublishInvoicePaid(ctx context.Context, inv *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInvoicePaid", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInvoicePaid indicates an expected call of PublishInvoicePaid.
func (mr *MockEventPublisherMockRecorder) PublishInvoicePaid(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInvoicePaid", reflect.TypeOf((*MockEventPublisher)(nil).PublishInvoicePaid), ctx, inv)
}
