// Code generated by MockGen. DO NOT EDIT.
// Source: overdue_worker.go
//
// Generated by this command:
//
//	mockgen -package=mock_usecase -source=overdue_worker.go -destination=../../_mock/usecase/overdue_worker_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ajiperdana/parkir-pintar/services/billing/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOverdueInvoiceRepo is a mock of OverdueInvoiceRepo interface.
type MockOverdueInvoiceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOverdueInvoiceRepoMockRecorder
	isgomock struct{}
}

// MockOverdueInvoiceRepoMockRecorder is the mock recorder for MockOverdueInvoiceRepo.
type MockOverdueInvoiceRepoMockRecorder struct {
	mock *MockOverdueInvoiceRepo
}

// NewMockOverdueInvoiceRepo creates a new mock instance.
func NewMockOverdueInvoiceRepo(ctrl *gomock.Controller) *MockOverdueInvoiceRepo {
	mock := &MockOverdueInvoiceRepo{ctrl: ctrl}
	mock.recorder = &MockOverdueInvoiceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverdueInvoiceRepo) EXPECT() *MockOverdueInvoiceRepoMockRecorder {
	return m.recorder
}

// FindOverdueCandidates mocks base method.
func (m *MockOverdueInvoiceRepo) FindOverdueCandidates(ctx context.Context, issuedBefore time.Time, limit int) ([]*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverdueCandidates", ctx, issuedBefore, limit)
	ret0, _ := ret[0].([]*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverdueCandidates indicates an expected call of FindOverdueCandidates.
func (mr *MockOverdueInvoiceRepoMockRecorder) FindOverdueCandidates(ctx, issuedBefore, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverdueCandidates", reflect.TypeOf((*MockOverdueInvoiceRepo)(nil).FindOverdueCandidates), ctx, issuedBefore, limit)
}

// Save mocks base method.
func (m *MockOverdueInvoiceRepo) Save(ctx context.Context, inv *domain.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOverdueInvoiceRepoMockRecorder) Save(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOverdueInvoiceRepo)(nil).Save), ctx, inv)
}
