// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package=mock_usecase -source=service.go -destination=../../_mock/usecase/service_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	midtrans "github.com/ajiperdana/parkir-pintar/services/payment/internal/adapter/midtrans"
	domain "github.com/ajiperdana/parkir-pintar/services/payment/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// GetByGatewayRef mocks base method.
func (m *MockRepo) GetByGatewayRef(ctx context.Context, ref string) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGatewayRef", ctx, ref)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGatewayRef indicates an expected call of GetByGatewayRef.
func (mr *MockRepoMockRecorder) GetByGatewayRef(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGatewayRef", reflect.TypeOf((*MockRepo)(nil).GetByGatewayRef), ctx, ref)
}

// GetByID mocks base method.
func (m *MockRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepo)(nil).GetByID), ctx, id)
}

// GetByInvoiceID mocks base method.
func (m *MockRepo) GetByInvoiceID(ctx context.Context, invoiceID uuid.UUID) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInvoiceID", ctx, invoiceID)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInvoiceID indicates an expected call of GetByInvoiceID.
func (mr *MockRepoMockRecorder) GetByInvoiceID(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInvoiceID", reflect.TypeOf((*MockRepo)(nil).GetByInvoiceID), ctx, invoiceID)
}

// LogWebhook mocks base method.
func (m *MockRepo) LogWebhook(ctx context.Context, paymentID *uuid.UUID, source, signature string, raw []byte, verified bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogWebhook", ctx, paymentID, source, signature, raw, verified)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogWebhook indicates an expected call of LogWebhook.
func (mr *MockRepoMockRecorder) LogWebhook(ctx, paymentID, source, signature, raw, verified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogWebhook", reflect.TypeOf((*MockRepo)(nil).LogWebhook), ctx, paymentID, source, signature, raw, verified)
}

// Save mocks base method.
func (m *MockRepo) Save(ctx context.Context, p *domain.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), ctx, p)
}

// MockInvoiceLookup is a mock of InvoiceLookup interface.
type MockInvoiceLookup struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceLookupMockRecorder
	isgomock struct{}
}

// MockInvoiceLookupMockRecorder is the mock recorder for MockInvoiceLookup.
type MockInvoiceLookupMockRecorder struct {
	mock *MockInvoiceLookup
}

// NewMockInvoiceLookup creates a new mock instance.
func NewMockInvoiceLookup(ctrl *gomock.Controller) *MockInvoiceLookup {
	mock := &MockInvoiceLookup{ctrl: ctrl}
	mock.recorder = &MockInvoiceLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceLookup) EXPECT() *MockInvoiceLookupMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockInvoiceLookup) Get(ctx context.Context, invoiceID uuid.UUID) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, invoiceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockInvoiceLookupMockRecorder) Get(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInvoiceLookup)(nil).Get), ctx, invoiceID)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishPaymentFailed mocks base method.
func (m *MockEventPublisher) PublishPaymentFailed(ctx context.Context, p *domain.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentFailed", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentFailed indicates an expected call of PublishPaymentFailed.
func (mr *MockEventPublisherMockRecorder) PublishPaymentFailed(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentFailed", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentFailed), ctx, p)
}

// PublishPaymentSucceeded mocks base method.
func (m *MockEventPublisher) PublishPaymentSucceeded(ctx context.Context, p *domain.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentSucceeded", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentSucceeded indicates an expected call of PublishPaymentSucceeded.
func (mr *MockEventPublisherMockRecorder) PublishPaymentSucceeded(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentSucceeded", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentSucceeded), ctx, p)
}

// MockGatewayClient is a mock of GatewayClient interface.
type MockGatewayClient struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayClientMockRecorder
	isgomock struct{}
}

// MockGatewayClientMockRecorder is the mock recorder for MockGatewayClient.
type MockGatewayClientMockRecorder struct {
	mock *MockGatewayClient
}

// NewMockGatewayClient creates a new mock instance.
func NewMockGatewayClient(ctrl *gomock.Controller) *MockGatewayClient {
	mock := &MockGatewayClient{ctrl: ctrl}
	mock.recorder = &MockGatewayClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayClient) EXPECT() *MockGatewayClientMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockGatewayClient) Charge(ctx context.Context, req midtrans.ChargeRequest) (*midtrans.ChargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, req)
	ret0, _ := ret[0].(*midtrans.ChargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Charge indicates an expected call of Charge.
func (mr *MockGatewayClientMockRecorder) Charge(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockGatewayClient)(nil).Charge), ctx, req)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
